[package]
name = "pig_latin"
version = "0.1.0"
authors = ["frdwhite24 <fred-white@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
