[package]
name = "convert_temps"
version = "0.1.0"
authors = ["Fred White <f.white@enian.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
